version: '3'
services:
    nginx:
        build:
            context: ../../docker/nginx
            args:
                - SYMFONY_VERSION=${SYMFONY_VERSION}
        ports:
            - "${PORT}:80"
        links:
            - php
        volumes_from:
            - php
        volumes:
            - "../../data/logs/${PROJECT_NAME}/nginx/:/var/log/nginx:cached"

    php:
        build: ../../docker/php-fpm
        ports:
            - '9002:9000'
        volumes:
            - "./:/var/www/symfony:cached"
            - "../../data/logs/${PROJECT_NAME}/symfony/:/var/www/symfony/var/logs:cached"
            - ~/.ssh:/home/user/.ssh
