version: '3'
services:
    nginx:
        build:
            context: ../../docker/nginx
            args:
                - SYMFONY_VERSION=${SYMFONY_VERSION}
        ports:
            - "${PORT}:80"
        links:
            - php
#            - redis
        volumes_from:
            - php
        volumes:
            - "../../data/logs/${PROJECT_NAME}/nginx/:/var/log/nginx:cached"
#        networks:
#            - mm-network

    php:
        build: ../../docker/php-fpm
        ports:
            - '9002:9000'
        volumes:
            - "./:/var/www/symfony"
            - "../../data/logs/${PROJECT_NAME}/symfony/:/var/www/symfony/var/logs:cached"
            - ~/.ssh:/home/user/.ssh
#        links:
#            - mysql
#        networks:
#            - mm-network


#    mysql:
#        image: mysql:5.7
#        ports:
#            - "3307:3306"
#        environment:
#            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
#            MYSQL_USER: 'root'
#        volumes:
#            - ../data/mysql:/var/lib/mysql
#
#    phpmyadmin:
#        image: phpmyadmin/phpmyadmin
#        ports:
#            - "8080:80"
#        links:
#            - mysql
#        environment:
#            PMA_HOST: mysql

#    nodejs:
#        build: nodejs
#        volumes_from:
#            - php
#        command: "yarn build"
#        ports:
#            - 8089:8089 # Port pour webpack
#            - 3000:3000 # Port pour BrowserSync
#        command: bash -c "yarn && yarn dev"

#    redis:
#        image: redis:alpine
#        ports:
#            - 6379:6379
              
#networks:
#    mm-network:
#        driver: bridge
#    default:
#        external:
#            name: nginx-proxy